-- ==========================================
-- WILLS AWESOME GENERATOR FROM JSON FILES YAYAYAYAY
-- ==========================================

-- 
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('BIOL 101', 'BIOL', '101', 'Concepts of Biology');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('BIOL 140', 'BIOL', '140', 'Foundations of Biology: Ecology and Evolution');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('BIOL 141', 'BIOL', '141', 'Foundations of Biology: Cells, Energy and Organisms');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('BIOL 251', 'BIOL', '251', 'Human Anatomy and Physiology I');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('BIOL 273', 'BIOL', '273', 'Microbiology for Allied Health');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('BIOL 302', 'BIOL', '302', 'Molecular and General Genetics');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('BIOL 303', 'BIOL', '303', 'Cell Biology');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('BIOL 430', 'BIOL', '430', 'Biological Chemistry');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CHEM 100', 'CHEM', '100', 'The Chemical World');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CHEM 101', 'CHEM', '101', 'Principles of Chemistry I');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CHEM 102', 'CHEM', '102', 'Principles of Chemistry II');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CHEM 120', 'CHEM', '120', 'Introduction to General, Organic, and Biochemistry');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CHEM 300', 'CHEM', '300', 'Analytical Chemistry');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CHEM 303', 'CHEM', '303', 'Physical Chemistry for the Biochemical Sciences');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CHEM 351', 'CHEM', '351', 'Organic Chemistry I');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CHEM 352', 'CHEM', '352', 'Organic Chemistry II');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CMPE 212', 'CMPE', '212', 'Principles of Digital Design');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CMPE 306', 'CMPE', '306', 'Introductory Circuit Theory');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CMPE 314', 'CMPE', '314', 'Principles of Electronic Circuits');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CMSC 201', 'CMSC', '201', 'Computer Science I');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CMSC 202', 'CMSC', '202', 'Computer Science II');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CMSC 203', 'CMSC', '203', 'Discrete Structures');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CMSC 313', 'CMSC', '313', 'Computer Organization and Assembly Language Programming');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CMSC 331', 'CMSC', '331', 'Principles of Programming Languages');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CMSC 341', 'CMSC', '341', 'Data Structures');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CMSC 411', 'CMSC', '411', 'Computer Architecture');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CMSC 421', 'CMSC', '421', 'Principles of Operating Systems');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CMSC 426', 'CMSC', '426', 'Principles of Computer Security');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('CMSC 441', 'CMSC', '441', 'Design and Analysis of Algorithms');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('ECON 101', 'ECON', '101', 'Principles of Microeconomics');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('ECON 102', 'ECON', '102', 'Principles of Macroeconomics');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('GES 102', 'GES', '102', 'People, Place, and Environment: A Global Geographic Perspective');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('GES 110', 'GES', '110', 'The Changing Earth: Climate, Ecosystems, Water, and Landscapes');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('GES 120', 'GES', '120', 'Environmental Science and Conservation');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('GES 286', 'GES', '286', 'Exploring the Environment: A Geo-Spatial Perspective');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('GES 386', 'GES', '386', 'Introduction to Geographic Information Systems');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('GES 488', 'GES', '488', 'Spatial Data Analysis and GIS Applications');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('IS 147', 'IS', '147', 'Introduction to Computer Programming');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('IS 247', 'IS', '247', 'Computer Programming II');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('IS 300', 'IS', '300', 'Management Information Systems');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('IS 310', 'IS', '310', 'Software and Hardware Concepts');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('IS 451', 'IS', '451', 'Network Design and Management');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('MATH 104', 'MATH', '104', 'Quantitative Literacy');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('MATH 106', 'MATH', '106', 'Algebra and Elementary Functions');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('MATH 150', 'MATH', '150', 'Precalculus Mathematics');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('MATH 151', 'MATH', '151', 'Calculus and Analytic Geometry I');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('MATH 152', 'MATH', '152', 'Calculus and Analytic Geometry II');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('MATH 155', 'MATH', '155', 'Applied Calculus');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('MATH 215', 'MATH', '215', 'Applied Finite Mathematics');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('MATH 221', 'MATH', '221', 'Introduction to Linear Algebra');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('MATH 225', 'MATH', '225', 'Introduction to Differential Equations');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('MATH 251', 'MATH', '251', 'Multivariable Calculus');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('MATH 300', 'MATH', '300', 'Introduction to Mathematical Reasoning');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('MATH 301', 'MATH', '301', 'Introduction to Contemporary Mathematics');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('PHYS 111', 'PHYS', '111', 'Basic Physics I');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('PHYS 112', 'PHYS', '112', 'Basic Physics II');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('PHYS 121', 'PHYS', '121', 'Introductory Physics I');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('PHYS 122', 'PHYS', '122', 'Introductory Physics II');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('SCI 100', 'SCI', '100', 'Science of Water; An Interdisciplinary Study');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('SPAN 101', 'SPAN', '101', 'Elementary Spanish I');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('SPAN 102', 'SPAN', '102', 'Elementary Spanish II');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('SPAN 201', 'SPAN', '201', 'Intermediate Spanish I');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('SPAN 202', 'SPAN', '202', 'Intermediate Spanish II');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('STAT 121', 'STAT', '121', 'Introduction to Statistics for the Social Sciences');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('STAT 350', 'STAT', '350', 'Statistics with Applications in the Biological Sciences');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('STAT 351', 'STAT', '351', 'Applied Statistics for Business and Economics');
INSERT OR IGNORE INTO course (course_code, department, course_number, long_title) VALUES ('STAT 355', 'STAT', '355', 'Introduction to Probability and Statistics for Scientists and Engineers');

-- tutor section
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_ABE', 'Abe', 'TBD', 'Abe');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_ADAMO', 'Adamo', 'TBD', 'Adamo');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_AKANKSHA', 'Akanksha', 'TBD', 'Akanksha');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_ANGELA', 'Angela', 'TBD', 'Angela');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_AREN', 'Aren', 'TBD', 'Aren');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_AVI', 'Avi', 'TBD', 'Avi');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_AYA', 'Aya', 'TBD', 'Aya');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_BRUNO', 'Bruno', 'TBD', 'Bruno');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_CHELSEA', 'Chelsea', 'TBD', 'Chelsea');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_CHIARA', 'Chiara', 'TBD', 'Chiara');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_DANI', 'Dani', 'TBD', 'Dani');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_ELVIS', 'Elvis', 'TBD', 'Elvis');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_HIMANI', 'Himani', 'TBD', 'Himani');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_IAN', 'Ian', 'TBD', 'Ian');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_INI', 'Ini', 'TBD', 'Ini');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_INIYA', 'Iniya', 'TBD', 'Iniya');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_JAVAN', 'Javan', 'TBD', 'Javan');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_JOSEPH', 'Joseph', 'TBD', 'Joseph');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_KAREN', 'Karen', 'TBD', 'Karen');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_KODI', 'Kodi', 'TBD', 'Kodi');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_LILLIAN', 'Lillian', 'TBD', 'Lillian');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_LILY', 'Lily', 'TBD', 'Lily');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_MANAV', 'Manav', 'TBD', 'Manav');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_MAX A.', 'Max A.', 'TBD', 'Max A.');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_MAX M.', 'Max M.', 'TBD', 'Max M.');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_MICHAEL', 'Michael', 'TBD', 'Michael');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_MOLEMO', 'Molemo', 'TBD', 'Molemo');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_MOLLY', 'Molly', 'TBD', 'Molly');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_MOYO', 'Moyo', 'TBD', 'Moyo');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_O’TEGA', 'O’Tega', 'TBD', 'O’Tega');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_RANIA', 'Rania', 'TBD', 'Rania');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_SHAKIB', 'Shakib', 'TBD', 'Shakib');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_SHAYAN', 'Shayan', 'TBD', 'Shayan');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_SHRIKANT', 'Shrikant', 'TBD', 'Shrikant');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_SINA', 'Sina', 'TBD', 'Sina');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_SOPHIA', 'Sophia', 'TBD', 'Sophia');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_SUSANNA', 'Susanna', 'TBD', 'Susanna');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_THEO', 'Theo', 'TBD', 'Theo');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_TRISTAN', 'Tristan', 'TBD', 'Tristan');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_ZACH', 'Zach', 'TBD', 'Zach');
INSERT OR IGNORE INTO tutor (student_ID, first_name, last_name, preferred_name) VALUES ('ID_ZOYA', 'Zoya', 'TBD', 'Zoya');

-- shifts and the middle table thingy
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (1, 'ID_SUSANNA', 'Monday', '11:00', '13:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (1, 'BIOL 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (1, 'BIOL 140');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (1, 'BIOL 141');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (1, 'BIOL 302');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (1, 'CHEM 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (1, 'CHEM 351');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (1, 'PHYS 111');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (2, 'ID_LILLIAN', 'Monday', '13:00', '14:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (2, 'BIOL 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (2, 'BIOL 140');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (2, 'BIOL 141');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (2, 'CHEM 351');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (3, 'ID_LILLIAN', 'Wednesday', '16:00', '18:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (3, 'BIOL 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (3, 'BIOL 140');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (3, 'BIOL 141');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (3, 'CHEM 351');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (4, 'ID_ANGELA', 'Monday', '16:00', '17:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (4, 'BIOL 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (4, 'BIOL 140');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (4, 'BIOL 141');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (4, 'BIOL 302');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (4, 'BIOL 303');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (4, 'CHEM 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (4, 'CHEM 102');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (4, 'CHEM 351');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (5, 'ID_ANGELA', 'Wednesday', '16:30', '18:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (5, 'BIOL 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (5, 'BIOL 140');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (5, 'BIOL 141');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (5, 'BIOL 302');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (5, 'BIOL 303');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (5, 'CHEM 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (5, 'CHEM 102');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (5, 'CHEM 351');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (6, 'ID_ZOYA', 'Tuesday', '13:00', '16:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (6, 'BIOL 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (6, 'BIOL 140');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (6, 'BIOL 141');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (6, 'BIOL 302');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (6, 'BIOL 303');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (6, 'BIOL 430');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (7, 'ID_ZOYA', 'Thursday', '13:00', '16:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (7, 'BIOL 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (7, 'BIOL 140');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (7, 'BIOL 141');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (7, 'BIOL 302');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (7, 'BIOL 303');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (7, 'BIOL 430');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (8, 'ID_SHAKIB', 'Thursday', '12:30', '14:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (8, 'BIOL 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (8, 'BIOL 140');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (8, 'BIOL 141');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (8, 'BIOL 302');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (8, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (8, 'MATH 155');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (9, 'ID_AVI', 'Thursday', '13:00', '16:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'BIOL 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'BIOL 140');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'BIOL 141');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'BIOL 302');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'BIOL 303');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'CHEM 100');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'CHEM 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'CHEM 102');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'CHEM 120');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'CHEM 300');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'CHEM 303');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'MATH 104');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'MATH 106');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'MATH 150');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'MATH 155');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'MATH 215');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'MATH 300');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'MATH 301');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'PHYS 121');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'STAT 121');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'STAT 350');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'STAT 351');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (9, 'STAT 355');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (10, 'ID_TRISTAN', 'Wednesday', '11:00', '13:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (10, 'BIOL 140');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (10, 'BIOL 141');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (10, 'BIOL 302');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (10, 'BIOL 303');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (10, 'CHEM 351');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (11, 'ID_TRISTAN', 'Thursday', '11:00', '12:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (11, 'BIOL 140');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (11, 'BIOL 141');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (11, 'BIOL 302');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (11, 'BIOL 303');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (11, 'CHEM 351');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (12, 'ID_CHELSEA', 'Tuesday', '12:30', '13:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (12, 'BIOL 251');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (12, 'BIOL 273');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (12, 'MATH 106');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (12, 'STAT 121');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (13, 'ID_MOYO', 'Tuesday', '17:00', '18:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (13, 'BIOL 251');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (13, 'BIOL 273');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (13, 'CHEM 120');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (13, 'STAT 121');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (14, 'ID_MOYO', 'Wednesday', '17:00', '18:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (14, 'BIOL 251');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (14, 'BIOL 273');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (14, 'CHEM 120');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (14, 'STAT 121');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (15, 'ID_MOYO', 'Thursday', '17:00', '18:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (15, 'BIOL 251');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (15, 'BIOL 273');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (15, 'CHEM 120');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (15, 'STAT 121');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (16, 'ID_THEO', 'Monday', '13:00', '15:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (16, 'CHEM 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (16, 'CHEM 102');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (16, 'CHEM 300');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (16, 'CHEM 351');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (16, 'CHEM 352');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (17, 'ID_MOLEMO', 'Monday', '15:00', '17:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (17, 'CHEM 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (17, 'CHEM 102');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (17, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (17, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (17, 'MATH 225');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (17, 'MATH 251');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (18, 'ID_MOLEMO', 'Friday', '13:00', '14:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (18, 'CHEM 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (18, 'CHEM 102');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (18, 'MATH 225');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (18, 'MATH 251');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (19, 'ID_INIYA', 'Tuesday', '13:00', '14:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (19, 'CHEM 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (19, 'CHEM 102');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (20, 'ID_INIYA', 'Tuesday', '16:00', '17:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (20, 'CHEM 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (20, 'CHEM 102');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (21, 'ID_INIYA', 'Wednesday', '11:00', '12:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (21, 'CHEM 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (21, 'CHEM 102');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (22, 'ID_SHAYAN', 'Wednesday', '14:00', '16:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (22, 'CHEM 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (22, 'CHEM 102');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (22, 'CHEM 351');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (22, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (22, 'MATH 152');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (23, 'ID_SHAYAN', 'Friday', '13:00', '14:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (23, 'CHEM 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (23, 'CHEM 102');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (23, 'CHEM 351');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (23, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (23, 'MATH 152');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (24, 'ID_ZACH', 'Wednesday', '15:00', '17:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (24, 'CHEM 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (24, 'CHEM 102');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (24, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (24, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (24, 'PHYS 121');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (25, 'ID_ZACH', 'Thursday', '15:30', '17:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (25, 'CHEM 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (25, 'CHEM 102');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (25, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (25, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (25, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (25, 'PHYS 121');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (26, 'ID_ZACH', 'Friday', '11:00', '12:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (26, 'CHEM 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (26, 'CHEM 102');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (26, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (26, 'PHYS 121');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (27, 'ID_ZACH', 'Thursday', '15:00', '17:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (27, 'MATH 152');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (28, 'ID_ZACH', 'Wednesday', '15:30', '17:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (28, 'PHYS 111');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (29, 'ID_HIMANI', 'Thursday', '17:00', '18:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (29, 'CHEM 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (29, 'CHEM 102');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (29, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (29, 'PHYS 111');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (30, 'ID_HIMANI', 'Friday', '12:00', '13:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (30, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (30, 'PHYS 111');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (31, 'ID_AYA', 'Monday', '14:00', '16:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (31, 'CHEM 351');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (31, 'CHEM 352');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (32, 'ID_AYA', 'Thursday', '11:00', '13:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (32, 'CHEM 351');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (32, 'CHEM 352');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (33, 'ID_KAREN', 'Tuesday', '16:00', '17:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (33, 'CHEM 351');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (33, 'CHEM 352');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (33, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (33, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (33, 'MATH 155');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (33, 'STAT 350');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (34, 'ID_KAREN', 'Thursday', '16:00', '17:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (34, 'CHEM 351');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (34, 'CHEM 352');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (34, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (34, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (34, 'MATH 155');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (35, 'ID_KAREN', 'Friday', '11:30', '13:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (35, 'CHEM 351');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (35, 'CHEM 352');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (35, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (35, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (35, 'MATH 155');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (35, 'STAT 350');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (36, 'ID_KAREN', 'Thursday', '17:00', '18:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (36, 'STAT 350');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (37, 'ID_SHRIKANT', 'Monday', '11:00', '13:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (37, 'CMPE 212');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (37, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (37, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (37, 'CMSC 203');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (37, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (37, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (37, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (37, 'PHYS 121');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (37, 'PHYS 122');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (38, 'ID_SHRIKANT', 'Tuesday', '13:00', '14:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (38, 'CMPE 212');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (38, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (38, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (38, 'CMSC 203');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (38, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (38, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (38, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (38, 'PHYS 121');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (38, 'PHYS 122');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (39, 'ID_SHRIKANT', 'Tuesday', '14:45', '15:45');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (39, 'CMPE 212');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (39, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (39, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (39, 'CMSC 203');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (39, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (39, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (39, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (39, 'PHYS 121');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (39, 'PHYS 122');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (40, 'ID_SHRIKANT', 'Thursday', '15:00', '16:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (40, 'CMPE 212');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (40, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (40, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (40, 'CMSC 203');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (40, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (40, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (40, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (40, 'PHYS 121');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (40, 'PHYS 122');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (41, 'ID_SHRIKANT', 'Thursday', '17:00', '18:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (41, 'CMPE 212');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (41, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (41, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (41, 'CMSC 203');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (41, 'CMSC 341');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (41, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (41, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (41, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (41, 'PHYS 121');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (41, 'PHYS 122');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (42, 'ID_SHRIKANT', 'Friday', '11:00', '14:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (42, 'CMPE 212');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (42, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (42, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (42, 'CMSC 203');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (42, 'CMSC 341');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (42, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (42, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (42, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (42, 'PHYS 121');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (42, 'PHYS 122');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (43, 'ID_JAVAN', 'Monday', '13:00', '16:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (43, 'CMPE 212');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (43, 'CMPE 306');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (43, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (43, 'CMSC 202');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (44, 'ID_JAVAN', 'Wednesday', '13:00', '16:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (44, 'CMPE 212');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (44, 'CMPE 306');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (44, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (44, 'CMSC 202');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (45, 'ID_ELVIS', 'Monday', '11:00', '14:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (45, 'CMPE 306');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (45, 'CMPE 314');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (46, 'ID_ELVIS', 'Wednesday', '11:00', '14:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (46, 'CMPE 306');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (46, 'CMPE 314');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (47, 'ID_IAN', 'Monday', '11:00', '12:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (47, 'CMPE 314');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (47, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (47, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (47, 'CMSC 341');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (47, 'CMSC 411');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (47, 'CMSC 421');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (47, 'CMSC 426');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (48, 'ID_IAN', 'Tuesday', '11:30', '14:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (48, 'CMPE 314');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (48, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (48, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (48, 'CMSC 341');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (48, 'CMSC 411');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (48, 'CMSC 421');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (48, 'CMSC 426');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (49, 'ID_IAN', 'Wednesday', '11:00', '12:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (49, 'CMPE 314');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (49, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (49, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (49, 'CMSC 341');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (49, 'CMSC 411');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (49, 'CMSC 421');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (49, 'CMSC 426');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (50, 'ID_IAN', 'Thursday', '11:30', '14:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (50, 'CMPE 314');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (50, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (50, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (50, 'CMSC 341');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (50, 'CMSC 411');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (50, 'CMSC 421');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (50, 'CMSC 426');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (51, 'ID_KODI', 'Monday', '11:00', '12:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (51, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (51, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (51, 'CMSC 203');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (51, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (51, 'MATH 225');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (51, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (51, 'PHYS 112');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (51, 'PHYS 121');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (51, 'PHYS 122');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (52, 'ID_KODI', 'Tuesday', '17:00', '18:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (52, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (52, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (52, 'CMSC 203');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (52, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (52, 'MATH 225');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (52, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (52, 'PHYS 112');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (52, 'PHYS 121');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (52, 'PHYS 122');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (53, 'ID_KODI', 'Wednesday', '11:00', '12:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (53, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (53, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (53, 'CMSC 203');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (53, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (53, 'MATH 225');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (53, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (53, 'PHYS 112');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (53, 'PHYS 121');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (53, 'PHYS 122');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (54, 'ID_KODI', 'Wednesday', '14:30', '15:45');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (54, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (54, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (54, 'CMSC 203');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (54, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (54, 'MATH 225');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (54, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (54, 'PHYS 112');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (54, 'PHYS 121');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (54, 'PHYS 122');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (55, 'ID_KODI', 'Thursday', '13:00', '14:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (55, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (55, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (55, 'CMSC 203');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (55, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (55, 'MATH 225');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (55, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (55, 'PHYS 112');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (55, 'PHYS 121');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (55, 'PHYS 122');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (56, 'ID_KODI', 'Thursday', '17:00', '18:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (56, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (56, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (56, 'CMSC 203');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (56, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (56, 'MATH 225');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (56, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (56, 'PHYS 112');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (56, 'PHYS 121');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (56, 'PHYS 122');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (57, 'ID_KODI', 'Friday', '11:00', '14:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (57, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (57, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (57, 'CMSC 203');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (57, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (57, 'MATH 225');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (57, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (57, 'PHYS 112');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (57, 'PHYS 121');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (57, 'PHYS 122');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (58, 'ID_MAX A.', 'Monday', '12:30', '14:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (58, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (58, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (58, 'CMSC 203');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (58, 'CMSC 331');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (58, 'CMSC 341');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (59, 'ID_MAX A.', 'Tuesday', '11:00', '14:15');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (59, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (59, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (59, 'CMSC 203');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (59, 'CMSC 331');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (59, 'CMSC 341');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (60, 'ID_MAX A.', 'Wednesday', '12:30', '14:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (60, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (60, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (60, 'CMSC 203');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (60, 'CMSC 331');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (60, 'CMSC 341');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (61, 'ID_MAX A.', 'Thursday', '11:00', '14:15');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (61, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (61, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (61, 'CMSC 203');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (61, 'CMSC 331');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (61, 'CMSC 341');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (62, 'ID_MAX A.', 'Thursday', '16:00', '18:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (62, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (62, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (62, 'CMSC 203');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (62, 'CMSC 341');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (63, 'ID_SINA', 'Monday', '14:30', '17:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (63, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (63, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (63, 'CMSC 341');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (63, 'CMSC 411');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (63, 'CMSC 421');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (63, 'CMSC 426');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (63, 'CMSC 441');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (64, 'ID_SINA', 'Tuesday', '12:30', '17:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (64, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (64, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (64, 'CMSC 341');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (64, 'CMSC 411');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (64, 'CMSC 421');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (64, 'CMSC 426');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (64, 'CMSC 441');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (65, 'ID_SINA', 'Thursday', '12:30', '17:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (65, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (65, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (65, 'CMSC 341');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (65, 'CMSC 411');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (65, 'CMSC 421');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (65, 'CMSC 426');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (65, 'CMSC 441');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (66, 'ID_SINA', 'Friday', '11:00', '14:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (66, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (66, 'CMSC 202');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (66, 'CMSC 341');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (66, 'CMSC 411');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (66, 'CMSC 421');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (66, 'CMSC 426');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (66, 'CMSC 441');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (67, 'ID_LILY', 'Monday', '15:00', '18:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (67, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (67, 'CMSC 202');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (68, 'ID_LILY', 'Wednesday', '14:45', '15:45');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (68, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (68, 'CMSC 202');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (69, 'ID_AREN', 'Wednesday', '11:00', '12:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (69, 'CMSC 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (69, 'CMSC 203');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (69, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (69, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (69, 'MATH 225');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (69, 'MATH 251');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (69, 'MATH 300');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (69, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (69, 'PHYS 121');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (70, 'ID_AREN', 'Tuesday', '13:30', '17:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (70, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (70, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (70, 'MATH 225');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (70, 'MATH 300');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (70, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (70, 'PHYS 121');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (71, 'ID_AREN', 'Friday', '11:00', '13:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (71, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (71, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (71, 'MATH 225');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (71, 'MATH 300');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (71, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (71, 'PHYS 121');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (72, 'ID_MAX M.', 'Wednesday', '12:30', '15:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (72, 'CMSC 203');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (72, 'CMSC 313');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (72, 'CMSC 421');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (73, 'ID_ADAMO', 'Monday', '14:30', '16:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (73, 'ECON 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (73, 'ECON 102');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (73, 'MATH 155');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (74, 'ID_ADAMO', 'Wednesday', '16:00', '17:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (74, 'ECON 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (74, 'ECON 102');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (74, 'MATH 155');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (75, 'ID_ADAMO', 'Thursday', '16:00', '18:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (75, 'ECON 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (75, 'ECON 102');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (75, 'MATH 155');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (76, 'ID_BRUNO', 'Monday', '11:00', '13:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (76, 'IS 147');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (76, 'IS 310');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (76, 'IS 451');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (77, 'ID_BRUNO', 'Monday', '16:00', '18:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (77, 'IS 147');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (77, 'IS 310');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (77, 'IS 451');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (78, 'ID_BRUNO', 'Wednesday', '11:00', '13:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (78, 'IS 147');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (78, 'IS 310');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (78, 'IS 451');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (79, 'ID_BRUNO', 'Wednesday', '16:00', '18:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (79, 'IS 147');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (79, 'IS 310');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (79, 'IS 451');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (80, 'ID_SOPHIA', 'Tuesday', '16:00', '18:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (80, 'IS 147');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (80, 'IS 247');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (80, 'IS 300');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (80, 'IS 310');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (81, 'ID_SOPHIA', 'Thursday', '16:00', '18:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (81, 'IS 147');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (81, 'IS 247');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (81, 'IS 300');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (81, 'IS 310');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (82, 'ID_MICHAEL', 'Monday', '11:30', '12:45');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (82, 'MATH 106');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (82, 'MATH 150');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (82, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (82, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (82, 'MATH 225');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (82, 'MATH 251');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (83, 'ID_MICHAEL', 'Tuesday', '11:00', '12:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (83, 'MATH 106');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (83, 'MATH 150');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (83, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (83, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (83, 'MATH 225');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (83, 'MATH 251');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (84, 'ID_MICHAEL', 'Wednesday', '11:15', '12:45');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (84, 'MATH 106');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (84, 'MATH 150');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (84, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (84, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (84, 'MATH 225');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (84, 'MATH 251');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (85, 'ID_INI', 'Monday', '13:00', '14:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (85, 'MATH 106');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (85, 'MATH 155');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (85, 'SCI 100');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (86, 'ID_INI', 'Thursday', '13:30', '14:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (86, 'MATH 106');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (86, 'MATH 155');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (86, 'SCI 100');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (87, 'ID_ABE', 'Monday', '14:30', '15:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (87, 'MATH 106');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (87, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (87, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (87, 'MATH 225');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (87, 'PHYS 122');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (88, 'ID_ABE', 'Tuesday', '14:00', '15:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (88, 'MATH 106');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (88, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (88, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (88, 'MATH 225');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (88, 'PHYS 122');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (89, 'ID_ABE', 'Wednesday', '14:30', '15:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (89, 'MATH 106');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (89, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (89, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (89, 'MATH 225');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (89, 'PHYS 122');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (90, 'ID_MANAV', 'Tuesday', '11:30', '13:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (90, 'MATH 106');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (90, 'MATH 150');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (90, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (90, 'MATH 155');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (91, 'ID_MANAV', 'Wednesday', '11:30', '13:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (91, 'MATH 106');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (91, 'MATH 150');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (91, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (91, 'MATH 155');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (92, 'ID_MANAV', 'Thursday', '11:30', '12:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (92, 'MATH 106');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (92, 'MATH 150');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (92, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (92, 'MATH 155');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (93, 'ID_AKANKSHA', 'Tuesday', '15:00', '16:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (93, 'MATH 106');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (93, 'MATH 150');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (93, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (93, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (93, 'MATH 251');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (93, 'MATH 300');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (93, 'STAT 355');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (94, 'ID_AKANKSHA', 'Wednesday', '13:00', '14:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (94, 'MATH 106');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (94, 'MATH 150');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (94, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (94, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (94, 'MATH 251');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (94, 'MATH 300');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (94, 'STAT 355');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (95, 'ID_AKANKSHA', 'Thursday', '15:00', '17:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (95, 'MATH 106');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (95, 'MATH 150');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (95, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (95, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (95, 'MATH 251');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (95, 'MATH 300');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (95, 'STAT 355');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (96, 'ID_AKANKSHA', 'Monday', '11:00', '12:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (96, 'MATH 300');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (96, 'STAT 355');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (97, 'ID_MOLLY', 'Wednesday', '16:00', '18:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (97, 'MATH 106');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (97, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (97, 'MATH 152');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (98, 'ID_MOLLY', 'Monday', '16:00', '18:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (98, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (98, 'MATH 152');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (99, 'ID_O’TEGA', 'Monday', '12:30', '14:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (99, 'MATH 150');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (99, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (99, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (99, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (99, 'PHYS 112');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (99, 'PHYS 121');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (99, 'PHYS 122');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (100, 'ID_O’TEGA', 'Monday', '16:00', '18:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (100, 'MATH 150');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (100, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (100, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (100, 'PHYS 111');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (100, 'PHYS 112');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (100, 'PHYS 121');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (100, 'PHYS 122');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (100, 'STAT 121');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (101, 'ID_O’TEGA', 'Monday', '00:30', '14:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (101, 'STAT 121');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (102, 'ID_DANI', 'Monday', '14:00', '16:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (102, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (102, 'PHYS 121');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (102, 'STAT 350');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (102, 'STAT 351');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (102, 'STAT 355');
INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (103, 'ID_DANI', 'Wednesday', '14:00', '16:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (103, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (103, 'PHYS 121');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (103, 'STAT 350');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (103, 'STAT 351');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (103, 'STAT 355');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (104, 'ID_RANIA', 'Monday', '16:00', '17:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (104, 'MATH 151');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (104, 'MATH 152');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (104, 'MATH 251');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (105, 'ID_CHIARA', 'Thursday', '15:00', '16:00');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (105, 'SPAN 101');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (105, 'SPAN 102');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (105, 'SPAN 201');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (105, 'SPAN 202');

INSERT INTO weekly_shift (shift_id, tutor_ID, day_of_week, start_time, end_time) VALUES (106, 'ID_JOSEPH', 'Wednesday', '12:45', '14:30');
INSERT INTO shift_course_junct (shift_id, course_code) VALUES (106, 'STAT 121');

